#
# This is a comment!
#

##
  And this is a multi-line comment
##

value.amazing > ups >> pepe: jajaja
value: pe: pe
&pepe: hola # comment
multi-line: "ajajaja, \' @$
ajajaj#"

list: [
  yes,
  awesome,
  language,
  jajaja: hola,
  12.042,
  [ # comment
    yes, no,
    ##
      inner mult-line comment
    ##
    [ amazing, 23.1232 ## and here ## ]
  ]
]

# this is a value
#value 'jajaja': test awesome !!! ajajaja # pepepe

##
in.line:
  test: 'oli rules'
end

deploy > zeus:
  &server: 'http://zeus.server.com' # strings can be quoted
  port: 9000 # number as primitive value
  retry: yes
  # nested block
  authentication:
    # lists can be implicit using commas
    tokens:
      - %1DOTnv6B9b]n7pbV535
      - p16O2$)9,Z63bD&Q-82d
    end
  end
end

# with commas you can create lists
message: Hello, World!

task (my-task):
  run 'sub-task':
    run:
      test: this is a name
    end
  end
end
##

##
run
  this is amazing -c 'asdas'
  Super happy
end
##
